version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  springboot:
    image: springboot-docker
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres
      spring.datasource.password: postgres
      security.basic.enabled: "false"
      management.security.enabled: "false"
    ports:
      - 8085:8080
    depends_on:
      - db